module.exports = {
  printWidth: 100,
  vueIndentScriptAndStyle: true,
  singleQuote: true,
  trailingComma: 'all',
  proseWrap: 'never',
  htmlWhitespaceSensitivity: 'strict',
  endOfLine: 'auto',
  tabWidth: 2,
  useTabs: false,
  semi: false,
  bracketSpacing: true,
  arrowParens: 'avoid',
  jsxBracketSameLine: true,
}
